config/routes.rb
Moneycalc::Application.routes.draw do
  get 'about' => 'staic_pages#about'
  devise_for :users
  resources :users, except: [ :new, :create ] do
    resources :transactions, only: [ :index, :new, :create, :destroy ]
  end

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new", :as => :sign_in
    get "sign_out", :to => "devise/sessions#destroy", :as => :sign_out
    get "sign_up", :to => "devise/registrations#new", :as => :sign_up
  end

  

  root 'staic_pages#home'             

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  validates :amount, presence: true

  after_create :inc_ballance
  after_destroy :dec_ballance

  private

  def get_user
  	@user = User.find_by(id: user_id)
  end

  def inc_ballance
  	get_user
  	new_balance = @user.balance + amount
  	@user.update_attribute(:balance, new_balance)
  end

  def dec_ballance
  	get_user
  	new_balance = @user.balance - amount
  	@user.update_attribute(:balance, new_balance)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates :name,  presence: true, length: { maximum: 50 }
  before_save { self.email = email.downcase }
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_register_parameters, if: :devise_controller?
  
  before_action :set_locale
 
  protected

	  def configure_register_parameters
	    devise_parameter_sanitizer.for(:sign_up) << :name
	  end
	  def set_locale
	    I18n.locale = params[:locale] || I18n.default_locale
	    I18n.default_locale = I18n.locale
	  end
end

app/controllers/staic_pages_controller.rb
class StaicPagesController < ApplicationController
  
  def home
  	@user = current_user
  	if @user
  		@transactions = @user.transactions.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  	end
  end

  def about
  	@users = User.all
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  respond_to :html, :json
  before_action :set_transaction, only: :destroy

  def index
    @user = params[:user_id] ? User.find_by_id(params[:user_id]) : current_user
    if @user
      @transactions = @user.transactions.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    end
  end

  def new
  	@transaction = current_user.transactions.build
  end

  def create
  	@transaction = current_user.transactions.create(transaction_params)
  	redirect_to root_path
  end

  def destroy
  	@transaction.destroy
  	redirect_to root_path
  end

  private

  def transaction_params
  	params.require(:transaction).permit(:amount, :comment, :user_id)
  end

  def set_transaction
  	@transaction = Transaction.find_by_id(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_if_admin, only: [:destroy]
  before_action :check_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def profile
    @user = current_user
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_if_admin
      render text: "Acsess denied", status: 403 unless current_user.admin?
    end

    def check_user
      render text: "Acsess denied", status: 403 unless current_user.id == @user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staic_pages_helper.rb
module StaicPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sign_in_sign_up.html.erb
<h1><%= link_to 'Sign in', sign_in_url %> or <%= link_to 'Sign up', sign_up_url %> to see this page</h1>

app/views/layouts/_users_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Balance</th>
      <th>Registration</th>
      <th></th>
      <% if current_user.admin? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.balance %></td>
        <td><%= user.created_at.strftime("%m/%d/%Y (%I:%M%p)")%></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <%= will_paginate @users %>
  </tbody>
</table>

<h3>Users count: <%= @users.count %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moneycalc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Moneycalc", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <% if I18n.locale == :en %>
              <li><%= link_to image_tag("ru.png"), :locale=>'ru'%></li>

            <% else %>
              <li><%= link_to image_tag("en.png"), :locale=>'en'%></li>

            <%end%>
            <% if current_user %>
              <li><%= link_to t('profile'), user_path(current_user.id) %></li>
              <li><%= link_to t('sign_out'), sign_out_url %></li>
            <% else %>
      			  <li><%= link_to t('sign_in'), sign_in_url %></li>
      			  <li><%= link_to t('sign_up'), sign_up_url %> </li>
      			<% end %>				
          </ul>
          <ul class="nav pull-left">
            <li><%= link_to t('home'), root_path %></li>
            <li><%= link_to t('about'), about_path %></li>
            <li><%= link_to t('users'), users_path %></li>
          </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/staic_pages/about.html.erb
<h1>About MoneyCalc</h1>
<h3>MoneyCalc is a simple web application for personal financial management.</h3>

<h4>MoneyCalc's basic functionalities:</h4>
<ul>
	<li>Entering data about expenses and incomes</li>
	<li>Editing expenses/incomes records</li>
	<li>Adjustment of balances</li>
	<li>Accounts support</li>
</ul>

<% if current_user %>
	<h1>Listing users</h1>
	<%= render 'layouts/users_list' %>
<% else%>
	<p>Users count: <%= @users.count %></p>
<% end%>

app/views/staic_pages/home.html.erb
<% if @user %>
  <div>  
    <p><%= t :hello %> <%= @user.name %>!</p>
    <p>Balance: <%= @user.balance %></p>
    <%= render 'transactions/list' %>
    <%= link_to t('add_new_transaction'), new_user_transaction_path(@user.id) %>
  </div>
<%else%>
  <div class="center hero-unit">
  <h1><%= t('welcome_to') %> MoneyCalc</h1>

  <%= link_to t('sign_in'), sign_in_path, class: "btn btn-large btn-primary" %>
  <br/>
  <%= t('or') %>
  <br/>
  <%= link_to t('sign_up'), sign_up_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/transactions/_form.html.erb
<%= form_for(@transaction, url: user_transactions_path(@transaction.user_id) ) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Created</th>
      <th>Amount</th>
      <th>Comment</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.strftime("%m/%d/%Y (%I:%M%p)") %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.comment%></td>
        <td><%= link_to 'Destroy', user_transaction_path(transaction.user_id, transaction.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= will_paginate @transactions %>
  </tbody>
</table>

app/views/transactions/index.html.erb
<% if @user.transactions.any?%>
  <h1>Listing transactions</h1>
  <%= render 'list' %>
  <h3>Balance: <%= @user.balance %></h3>
<% else %>
  <h1>Transactions not found...</h1>
<% end %>
<% if @user.id == current_user.id %>
  <%= link_to 'Create new transaction', new_user_transaction_path(user_id: @user.id)%>
<% end %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_info.html.erb
<p>
	<strong>Name:</strong>
	<%= @user.name %>
</p>
<p>
	<strong>Email:</strong>
	<%= @user.email %>
</p>
<p>
	<strong>Balance:</strong>
	<%= @user.balance %>
</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if current_user %>
	<h1>Listing users</h1>
	<%= render 'layouts/users_list' %>
<% else %>
	<%= render 'layouts/sign_in_sign_up' %>
<% end %>

app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
	<%= render 'info' %>
	<%= link_to 'Edit user info', edit_user_path(@user) %> | 
	<%= link_to 'Manage transactions', transactions_path %> 
	
<% else %>
	<%= render 'layouts/sign_in_sign_up' %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
	<%= render 'info' %>
	<% if current_user.admin? || current_user.id == @user.id %>
		<%= link_to 'Edit user info', edit_user_path(@user) %> |
		<%= link_to 'Manage transactions', user_transactions_path(@user) %> |
		
	<% end %>
<% else %>
	<%= render 'layouts/sign_in_sign_up' %>
<% end %>
<%= link_to 'Back', users_path %>